### ISSUE TITLE
Composer!

### ISSUE THREAD

**Issue by chalasr** [jubianchi/async-generator#2]
Hi,

There is pretty much 1month since you presented it @phptour, but when I try to browse your library on packagist, I get the following:

![](http://image.prntscr.com/image/8c3546e9542c4b858fc5e790e542c16a.png)

And worst when I try to require it :trollface: 
What about submit it on packagist?

Thank's for this cool lib!

**Comment by jubianchi** [comment]
ho you are right I totally forgot to push it to packagist! Gonna do this ASAP.

**Comment by chalasr** [comment]
Thank's @jubianchi, please keep me informed here or close this when it's done.

**Comment by jubianchi** [comment]
https://packagist.org/packages/jubianchi/async-generator

**Comment by chalasr** [comment]
👍  Thank's @jubianchi
