### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by mnapoli** [jubianchi/async-generator#3]
Hello! We are playing with this library, is it ready for a first stable (or even beta) version? (it will be slightly easier to install with Packagist)

**Comment by jubianchi** [comment]
@mnapoli as you may know I'm working on poe which is also a generator-based http framework. 

I will soon move everything there and issue a first beta release. 

I'll keep you updated on the status. If you want to contribute let me know I'll be really happy to have you as a contribuor :)

**Comment by mnapoli** [comment]
:+1: good to know, we were mostly trying it out for now (running sub-processes in parallel) thanks!

**Comment by jubianchi** [comment]
@mnapoli if it's only for concurrent processes, you should take a look at `proc_open` + `stream_select` ;)

Thanks BTW, let me know if you have any suggestion.
